# Generated by Django 5.2.1 on 2025-07-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='student_performance.classgroup'),
        ),
    ]
