# Generated by Django 5.2.1 on 2025-07-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratedassessment',
            unique_together={('student', 'category', 'area')},
        ),
        migrations.RemoveField(
            model_name='ratedassessment',
            name='exam',
        ),
    ]
