# Generated by Django 5.0 on 2025-06-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_owner_alter_document_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, max_length=700, unique=True),
        ),
    ]
