# Generated by Django 5.0 on 2025-07-01 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documentcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcategory',
            name='parent_category',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='documents.documentcategory'),
        ),
    ]
