# Generated by Django 5.0 on 2025-07-02 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_documentcategory_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentcategory'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='document',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.subcategory'),
        ),
    ]
