# Generated by Django 5.0 on 2025-07-02 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_category_remove_document_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='documents.documentcategory'),
        ),
    ]
