# Generated by Django 5.0 on 2025-07-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documentcategory_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
