# Generated by Django 5.2.1 on 2025-07-07 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0009_remove_document_slug_remove_documentcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.subcategory'),
        ),
    ]
